// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxwoU6Zcf4v0gn6rE2y1IDZ3xMCej7gq0',
    appId: '1:949531322633:web:f06dd2a96e0be0fb868bd8',
    messagingSenderId: '949531322633',
    projectId: 'chat-app-surya-01',
    authDomain: 'chat-app-surya-01.firebaseapp.com',
    storageBucket: 'chat-app-surya-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5oIN_j3lvFQyjFOBCPAgC34jJAIieSEg',
    appId: '1:949531322633:android:ade4fab2274d03f5868bd8',
    messagingSenderId: '949531322633',
    projectId: 'chat-app-surya-01',
    storageBucket: 'chat-app-surya-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3d3cF4mP_iU_TLpV6EoDvkr4ULsDAUy8',
    appId: '1:949531322633:ios:086fce60be6f7485868bd8',
    messagingSenderId: '949531322633',
    projectId: 'chat-app-surya-01',
    storageBucket: 'chat-app-surya-01.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3d3cF4mP_iU_TLpV6EoDvkr4ULsDAUy8',
    appId: '1:949531322633:ios:086fce60be6f7485868bd8',
    messagingSenderId: '949531322633',
    projectId: 'chat-app-surya-01',
    storageBucket: 'chat-app-surya-01.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxwoU6Zcf4v0gn6rE2y1IDZ3xMCej7gq0',
    appId: '1:949531322633:web:5f2b650c7e267413868bd8',
    messagingSenderId: '949531322633',
    projectId: 'chat-app-surya-01',
    authDomain: 'chat-app-surya-01.firebaseapp.com',
    storageBucket: 'chat-app-surya-01.firebasestorage.app',
  );
}
